// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(BeSpokedContext))]
    partial class BeSpokedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("backend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "100 Piedmont Park Dr, Atlanta, GA 30309",
                            FirstName = "David",
                            LastName = "Thompson",
                            Phone = "678-555-1001",
                            StartDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "250 Virginia Ave, Atlanta, GA 30306",
                            FirstName = "Sarah",
                            LastName = "Williams",
                            Phone = "678-555-1002",
                            StartDate = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "88 Ponce De Leon Ave, Atlanta, GA 30308",
                            FirstName = "Michael",
                            LastName = "Brown",
                            Phone = "770-555-1003",
                            StartDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "415 Grant Park Way, Atlanta, GA 30312",
                            FirstName = "Jessica",
                            LastName = "Davis",
                            Phone = "770-555-1004",
                            StartDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "60 Inman Park Ln, Atlanta, GA 30307",
                            FirstName = "Robert",
                            LastName = "Garcia",
                            Phone = "404-555-1005",
                            StartDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("backend.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeginDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 10.00m,
                            EndDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            BeginDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 15.00m,
                            EndDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3
                        },
                        new
                        {
                            Id = 3,
                            BeginDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 5.00m,
                            EndDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5
                        });
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QtyOnHand")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Manufacturer")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommissionPercentage = 10.00m,
                            Manufacturer = "Trek",
                            Name = "Trail Blazer 3000",
                            PurchasePrice = 1200.00m,
                            QtyOnHand = 10,
                            SalePrice = 1899.99m,
                            Style = "Mountain"
                        },
                        new
                        {
                            Id = 2,
                            CommissionPercentage = 12.00m,
                            Manufacturer = "Specialized",
                            Name = "Road Master Elite",
                            PurchasePrice = 2000.00m,
                            QtyOnHand = 7,
                            SalePrice = 3199.99m,
                            Style = "Road"
                        },
                        new
                        {
                            Id = 3,
                            CommissionPercentage = 8.00m,
                            Manufacturer = "Cannondale",
                            Name = "Urban Glide 500",
                            PurchasePrice = 600.00m,
                            QtyOnHand = 15,
                            SalePrice = 999.99m,
                            Style = "Hybrid"
                        },
                        new
                        {
                            Id = 4,
                            CommissionPercentage = 15.00m,
                            Manufacturer = "Giant",
                            Name = "Aero Speed Pro",
                            PurchasePrice = 3500.00m,
                            QtyOnHand = 4,
                            SalePrice = 5499.99m,
                            Style = "Road"
                        },
                        new
                        {
                            Id = 5,
                            CommissionPercentage = 9.00m,
                            Manufacturer = "Surly",
                            Name = "Fat Tire Explorer",
                            PurchasePrice = 900.00m,
                            QtyOnHand = 8,
                            SalePrice = 1499.99m,
                            Style = "Fat Bike"
                        });
                });

            modelBuilder.Entity("backend.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SalesDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalespersonCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalespersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalespersonId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Price = 1709.99m,
                            ProductId = 1,
                            SalesDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonCommission = 171.00m,
                            SalespersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            Price = 3199.99m,
                            ProductId = 2,
                            SalesDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonCommission = 384.00m,
                            SalespersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            Price = 849.99m,
                            ProductId = 3,
                            SalesDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonCommission = 68.00m,
                            SalespersonId = 1
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            Price = 5499.99m,
                            ProductId = 4,
                            SalesDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonCommission = 825.00m,
                            SalespersonId = 3
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            Price = 1709.99m,
                            ProductId = 1,
                            SalesDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonCommission = 171.00m,
                            SalespersonId = 2
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 1,
                            Price = 1424.99m,
                            ProductId = 5,
                            SalesDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonCommission = 128.25m,
                            SalespersonId = 3
                        });
                });

            modelBuilder.Entity("backend.Models.Salesperson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName", "Phone")
                        .IsUnique();

                    b.ToTable("Salespersons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Peachtree St, Atlanta, GA 30301",
                            FirstName = "James",
                            LastName = "Carter",
                            Manager = "Sarah Mitchell",
                            Phone = "404-555-0101",
                            StartDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Buckhead Ave, Atlanta, GA 30305",
                            FirstName = "Olivia",
                            LastName = "Chen",
                            Manager = "Sarah Mitchell",
                            Phone = "404-555-0202",
                            StartDate = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Midtown Blvd, Atlanta, GA 30308",
                            FirstName = "Marcus",
                            LastName = "Johnson",
                            Manager = "Sarah Mitchell",
                            Phone = "404-555-0303",
                            StartDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Decatur Rd, Atlanta, GA 30307",
                            FirstName = "Elena",
                            LastName = "Rodriguez",
                            Manager = "Sarah Mitchell",
                            Phone = "404-555-0404",
                            StartDate = new DateTime(2020, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TerminationDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("backend.Models.Discount", b =>
                {
                    b.HasOne("backend.Models.Product", "Product")
                        .WithMany("Discounts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("backend.Models.Sale", b =>
                {
                    b.HasOne("backend.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Salesperson", "Salesperson")
                        .WithMany("Sales")
                        .HasForeignKey("SalespersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Salesperson");
                });

            modelBuilder.Entity("backend.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("backend.Models.Salesperson", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
